version: '3.1'
services:
  app:
    container_name: springboot-postgresql
    image: bot
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    build:
      context: ./
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      - PGDATA=/src/resources/db.changelog
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres