server:
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${JDBC_DATABASE_USERNAME:postgres}
    password: ${JDBC_DATABASE_PASSWORD:root}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.globally_quoted_identifiers: true

telegram:
  name: SubManagementBot
  token: 5813502079:AAE82TJ2PoXJKQXEjw1OGv6WUG9OXgNMMPo
  chanel-id: -1001815692806
  support:
    chat-id: 438760453
